### ISSUE TITLE
This repo should be private

### ISSUE THREAD

**Issue by MarkWheelhouse** [andrei-alpha/pintos#2]
Dear Andrei,

Could you please help to maintain the academic integrity of the Computing course at Imperial by making this repository private on GitHub. At least one of our students has decided to copy some of your code and is thus missing out on the important educational experience that this project offers.

Best
Mark

**Comment by andrei-alpha** [comment]
Hi Mark,

Sure, thanks for letting me know, I will update the repository settings.

Best,
Andrei
